# Generated by Django 6.0.1 on 2026-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=200)),
                ('med_user', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('per_day_tabs', models.IntegerField()),
                ('total_tablet_count', models.IntegerField()),
            ],
        ),
    ]
