# Generated by Django 6.0.1 on 2026-01-07 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0002_remove_medicinedetails_med_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetails',
            name='med_user',
            field=models.CharField(default='Self', max_length=100),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='per_day_tabs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='total_tablet_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='total_tabs_packet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
