# Generated by Django 6.0.1 on 2026-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0003_medicinedetails_med_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='start_date',
            field=models.DateField(),
        ),
    ]
